[package]
name = "pjsekai-background-gen-core"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image.workspace = true
imageproc = "0.23.0"
once_cell.workspace = true
